{{- range $app, $details := .Values.applications }}
{{- if $details.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ $app }}
  namespace: argocd 
  annotations:
  {{- $annotations := dict }}
  {{- if and $details.annotations  $.Values.global.annotations }}
    {{- $annotations = mustMergeOverwrite ($.Values.global.annotations | deepCopy) $details.annotations }}
  {{- else if $details.annotations }}
    {{- $annotations = $details.annotations }}
  {{- else }}
    {{- $annotations = $.Values.global.annotations }}
  {{- end }}
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  labels:
  {{- $labels := dict }}
  {{- if and $details.labels  $.Values.global.labels }}
    {{- $labels = mustMergeOverwrite ($.Values.global.labels | deepCopy) $details.labels }}
  {{- else if $details.annotations }}
    {{- $labels = $details.annotations }}
  {{- else }}
    {{- $labels = $.Values.global.labels }}
  {{- end }}
  {{- if $labels }}
  labels:
  {{- end }}
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  project: {{ default "default" $details.project }}
  destination:
    server: https://kubernetes.default.svc
    {{- if $details.namespace }}
    namespace: {{ $details.namespace }}
    {{- end }}
  {{- if eq $details.type "helmMultiSource" }}
  sources:
  {{ else }}
  source:
  {{- end }}
  {{- if eq $details.type "helmMultiSource" }}
  - repoURL: {{ $details.chartURL }}
    chart: {{ $details.chart }}
    targetRevision: {{ $details.revision }}
    helm:
      valueFiles:
        {{- $sortedKeys := $details.values | keys | sortAlpha }}
        {{- range $key := $sortedKeys }}
        - $values/{{ default $.Values.global.basePathPrefix $details.basePathPrefix }}{{ index $details.values $key }}
        {{- end }}
  - repoURL: {{ default $.Values.global.repoURL $details.repoURL }}
    targetRevision: HEAD
    ref: values
  {{ else }}
    repoURL: {{ default $.Values.global.repoURL $details.repoURL }}
    targetRevision: {{ default "HEAD" $details.revision }}
    path: {{ default $.Values.global.basePathPrefix $details.basePathPrefix }}{{ $details.path }}
    {{- if eq $details.type "kustomize" }}
    kustomize:
    {{- range $option, $value := $details.kustomize }}
      {{ $option }}: {{ $value }}
    {{- end }}
    {{- else if eq $details.type "helmLocal" }}
    helm:
      valueFiles:
        {{- $sortedKeys := $details.values | keys | sortAlpha }}
        {{- range $key := $sortedKeys }}
        - {{ default $.Values.global.basePathPrefix $details.basePathPrefix }}{{ index $details.values $key }}
        {{- end }}
    {{- end }}
  {{- end }}
  syncPolicy:
    automated:
      prune: {{ default true $details.prune }}
      selfHeal: {{ default true $details.prune }}
    syncOptions:
    {{- $syncOptions := dict }}
    {{- if and $details.syncOptions  $.Values.global.syncOptions }}
      {{- $syncOptions = mustMergeOverwrite ($.Values.global.syncOptions | deepCopy) $details.syncOptions }}
    {{- else if $details.syncOptions }}
      {{- $syncOptions = $details.syncOptions }}
    {{- else }}
      {{- $syncOptions = $.Values.global.syncOptions }}
    {{- end }}
    {{- range $key, $value := $syncOptions }}
    - {{ $key }}={{ $value }}
    {{- end }}
---
{{- end }}
{{- end }}
