apiVersion: v1
data:
  internal.server: |
    example.org:53 {
      errors
      cache 30
      forward . 192.168.30.205
    }
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system