# https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: nginx-ca
  hosts:
  - name: sonarqube.example.org
  tls:
  - secretName: sonarqube-ingress-tls
    hosts:
    - sonarqube.example.org

# caCerts:
#   enabled: true
#   image: adoptopenjdk/openjdk11:alpine
#   secret: ca

jdbcOverwrite:
  # If enable the JDBC Overwrite, make sure to set `postgresql.enabled=false`
  enable: true
  # The JDBC url of the external DB
  jdbcUrl: "jdbc:postgresql://sonarqube-psql-rw/sonarqube?socketTimeout=1500"
  # The DB user that should be used for the JDBC connection
  jdbcUsername: "sonarqube"
  # Use this if you don't mind the DB password getting stored in plain text within the values file
  # jdbcPassword: "sonarPass"
  ## Alternatively, use a pre-existing k8s secret containing the DB password
  jdbcSecretName: "sonarqube-psql-app"
  ## and the secretValueKey of the password found within that secret
  jdbcSecretPasswordKey: "password"

## Configuration values for postgresql dependency
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
postgresql:
  # Enable to deploy the bitnami PostgreSQL chart
  enabled: false