apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-application-set
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "50"
spec:
  generators:
    - git:
        repoURL: https://github.com/grig777/k3s-argocd-provisioning
        revision: HEAD
        directories:
        - path: manifests/kustomize/overlays/prod/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/grig777/k3s-argocd-provisioning
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[4]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
