apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applications-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/grig777/k3s-argocd-provisioning
        revision: HEAD
        directories:
        - path: manifests/helm/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/grig777/k3s-argocd-provisioning
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-base.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
