ingress-nginx:
  controller:
    kind: DaemonSet
    # hostNetwork: true
    ## Use host ports 80 and 443
    ## Disabled by default
    hostPort:
      # -- Enable 'hostPort' or not
      enabled: true
      ports:
        # -- 'hostPort' http port
        http: 80
        # -- 'hostPort' https port
        https: 443
    admissionWebhooks:
      annotations: {}
      # ignore-check.kube-linter.io/no-read-only-rootfs: "This deployment needs write access to root filesystem".

      ## Additional annotations to the admission webhooks.
      ## These annotations will be added to the ValidatingWebhookConfiguration and
      ## the Jobs Spec of the admission webhooks.
      enabled: false