apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-minio-registery
  namespace: gitlab
spec:
  encryptedData:
    config: AgB/jZMZQSZEGm5ETXL/IhYzEdEoq8b6UUEzak9w5ytJ6zjakDdReGGXuJ0m5n6vBsZltG9TUyp0rU2m6gEG+YXAIK4kF3xWicsq9bdUsZ93fk2JFQTOIHln25xjEwgidmeWKBkeZg+5y8oIgDSXQEtMtUyodu+hJ7voPV/ZXSHBKbsCcSgv1XZmJEb/ilztfVRUt+N0o3nIz5QWEhZIQlF65WHeH3SwVvcNzzKLMnLY9/Z8iyaSNEFRTJ1yDCY9XFOxsr+HSUdG6dBVJxGGBvf6sROZa1LkxjT3LwbrrAsbm4tT4Neqpqc6iJ8EDjpaE23BPGCBxnzDOfGG4b2H2dlREdia86qMYBUQYGb1kcS1mA+1TdvshwHDyN4OSva4/0xKO9bg1IO7RIvhg5+OSTnbOIvsJhXvTNVjBMhsUs/gPsdLAplM5cykSIOjP9oYDKh/LByhBPx8WrB+jpBAV8aU8shgcIq17rKkjZByDI0nX/2k140eAqKVsuXESZ+bOniU3txLqC4FZxga2E0039q5aAAQpahzDFQFxNWob2WWU59WS5aUkMQNjjnfyoAC0GNAf6g+mKSVIkv34rswbbr6T4WnLsnzWBDc4aHX9Pkh3PCFWSgRhswfnOQQxapOr6zEwOAR/z+6b2Q1nKvUmiKPfibj4zXSDzyDXpEQal4PqYBfOpS2YgMplsUjt8V3z54yLUf5OwMcNP6KwiDAvKGjmss+Ha7GYVCgpD/BLur8KlHinJYp3m4q0VfPrikLYh+eAxe4unpZaRRi5AmFQJzV5W7GVSJUtTyLvXGk7DpfwNXvO0eNTfbPqr2LfHbbGaHjjBkrNi9oNpbyGRLftzBQ6yZc6qcbSnh6MHwqHkB2A9Lz5slGYR8Mf6LDgx5CFufBtNTWY9Ve4JbKRHOWEJJcsBHk3WSoIiiERdO3KQqWaMRF0VIJOoh0V+dDQQSad1rL4hmQVnHO19i3lsxNfECzhGp3KW8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitlab-minio-registery
      namespace: gitlab

