apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgresql
  namespace: gitlab
spec:
  instances: 3
  logLevel: trace
  enableSuperuserAccess: true
  startDelay: 60
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
    storageClass: directpv-min-io
  bootstrapInitDB:
    database: gitlab
    owner: gitlab
    