apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: opensearch
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.8.11
  containerLogRealPath: /var/log/containers
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    requests:
      cpu: 10m
      memory: 25Mi
    limits:
      cpu: 500m
      memory: 200Mi
  fluentBitConfigName: fluent-bit-only-config
  tolerations:
    - operator: Exists
---
# apiVersion: fluentbit.fluent.io/v1alpha2
# kind: ClusterFluentBitConfig
# metadata:
#   name: fluent-bit-only-config
#   labels:
#     app.kubernetes.io/name: fluent-bit
# spec:
#   service:
#     parsersFile: parsers.conf
#   inputSelector:
#     matchLabels:
#       fluentbit.fluent.io/enabled: "true"
#       fluentbit.fluent.io/mode: "fluentbit-only"
#   filterSelector:
#     matchLabels:
#       fluentbit.fluent.io/enabled: "true"
#       fluentbit.fluent.io/mode: "fluentbit-only"
#   outputSelector:
#     matchLabels:
#       fluentbit.fluent.io/enabled: "true"
#       fluentbit.fluent.io/mode: "fluentbit-only"

apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: cluster-fluentd-config
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces: 
  - kube-system
  - default
  - kafka
  - elastic
  - fluent
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/scope: "cluster"
      output.fluentd.fluent.io/enabled: "true"
---
# apiVersion: fluentbit.fluent.io/v1alpha2
# kind: ClusterInput
# metadata:
#   name: kubelet
#   labels:
#     fluentbit.fluent.io/enabled: "true"
#     fluentbit.fluent.io/mode: "fluentbit-only"
# spec:
#   systemd:
#     tag: service.kubelet
#     path: /var/log/journal
#     db: /fluent-bit/tail/kubelet.db
#     dbSync: Normal
#     systemdFilter:
#       - _SYSTEMD_UNIT=kubelet.service

apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: tail
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  tail:
    # tag: kube.*
    path: /var/log/containers/*.log
    # Exclude logs from util pod
    excludePath: /var/log/containers/utils_default_utils-*.log
    parser: docker   #If it is a containerd environment, then this item should be set to cri
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: systemd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  match: service.*
  filters:
  - lua:
      script:
        key: systemd.lua
        name: fluent-bit-lua
      call: add_time
      timeAsTable: true
---
apiVersion: v1
data:
  systemd.lua: |
    function add_time(tag, timestamp, record)
      new_record = {}
      timeStr = os.date("!*t", timestamp["sec"])
      t = string.format("%4d-%02d-%02dT%02d:%02d:%02d.%sZ", timeStr["year"], timeStr["month"], timeStr["day"], timeStr["hour"], timeStr["min"], timeStr["sec"], timestamp["nsec"])
      kubernetes = {}
      kubernetes["pod_name"] = record["_HOSTNAME"]
      kubernetes["container_name"] = record["SYSLOG_IDENTIFIER"]
      kubernetes["namespace_name"] = "kube-system"
      new_record["time"] = t
      new_record["log"] = record["MESSAGE"]
      new_record["kubernetes"] = kubernetes
      return 1, timestamp, new_record
    end
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-bit-lua
  name: fluent-bit-lua
  namespace: opensearch
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: es
  labels:
    # fluentbit.fluent.io/enabled: "true"
    # fluentbit.fluent.io/mode: "fluentbit-only"
    output.fluentd.fluent.io/scope: "cluster"
    output.fluentd.fluent.io/enabled: "true"
spec:
  # matchRegex: (?:kube|service)\.(.*)
  es:
    host: my-first-cluster-masters.opensearch
    port: 9200
    generateID: true
    logstashPrefix: fluent-log-fb-only
    logstashFormat: true
    timeKey: "@timestamp"
    httpUser: 
      valueFrom: 
        secretKeyRef:
          name: opensearch-admin-password
          key: username
    httpPassword:
      valueFrom: 
        secretKeyRef:
          name: opensearch-admin-password
          key: password
    tls:
      verify: false