---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-pod
spec:
  selector:
    matchLabels:
      name: all-nodes
  template:
    metadata:
      labels:
        name: all-nodes
    spec:
      volumes:
      - name: api-socket
        hostPath:
          path: /run/api.sock
      - name: apiclient
        hostPath:
          path: /usr/bin/apiclient
      containers:
      - name: sysctl-conf
        image: busybox
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && sleep inf"]
        securityContext:
          privileged: true
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: opensearch
spec:
  security:
    config:
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: my-first-cluster
    version: 2.3.0
    pluginsList: []
    drainDataNodes: true
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "2Gi"
         cpu: "100m"
      limits:
         memory: "512Mi"
         cpu: "1000m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "2000m"
         limits:
            memory: "4Gi"
            cpu: "2000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}