---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-pod
spec:
  selector:
    matchLabels:
      name: all-nodes
  template:
    metadata:
      labels:
        name: all-nodes
    spec:
      volumes:
      - name: api-socket
        hostPath:
          path: /run/api.sock
      - name: apiclient
        hostPath:
          path: /usr/bin/apiclient
      containers:
      - name: sysctl-conf
        image: busybox
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && sleep inf"]
        securityContext:
          privileged: true
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  general:
    serviceName: opensearch-cluster
    httpPort: 9200
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "1Gi"
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "3Gi"
            cpu: "2000m"
      persistence:
        pvc:
          storageClass: directpv-min-io
      # roles:
      #   - "data"
      #   - "master"