apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promethues
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 46.4.1
    helm:
      valueFiles:
      - $values/manifests/base/monitoring-apps/prometheus/helm-values/values.yaml
  - repoURL: 'https://github.com/grig777/k3s-argocd-provisioning.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
