apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.8.1
    helm:
      valueFiles:
      - $values/manifests/base/helm-apps/sealed-secrets/helm-values/values.yaml
  - repoURL: 'https://github.com/grig777/k3s-argocd-provisioning.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true