installCRDs: true
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "50m"
webhook:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "50m"
cainjector:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "50m"
startupapicheck:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "50m"