host: rocketchat.example.org
ingress:
  enabled: true
  pathType: Prefix
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: nginx-ca
  path: /
  tls: 
   - secretName: rocketchat-ingress-tls
     hosts:
       - rocketchat.example.org

registrationToken: f8be8f73-5d25-4acd-8ca7-1368b96cfc31

smtp:
  enabled: false
  username: asdasad
  password: asdasdasda
  host: nott.real.com
  port: 587